name: mico-competition
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python==3.8.13
  - pytorch==1.8.1
  - torchvision==0.9.1
  - torchcsprng==0.2.1
  - scikit-learn==1.1.3
  - matplotlib==3.6.1
  - pandas==1.5.1
  - pip:
    - datasets==2.6.1
    - transformers==4.24.0
